###############################################################################################
# 参考：https://spring.io/guides/gs/client-side-load-balancing/
# 代码地址（ 任选其一）
# http://git.oschina.net/itmuch/spring-cloud-study/tree/master/microserviceconsumer-movie-feign
# https://github.com/eacdy/spring-cloudstudy/tree/master/microservice-consumer-movie-feign
###############################################################################################
server:
  port: 18102
spring:
  application:
    name: micsvc-consumer-movie-feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8091/eureka/,http://peer2:8092/eureka
  instance:
    preferIpAddress: true
# 默认为true。如果设置为false，Ribbon将不
# 会从Eureka中获得服务列表，而是使用静态配置的服务列表。静态服务列表可使用：<client>.ribbon.listOfServers来指定。
# 参考：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#spring-cloud-ribbonwithout-eureka
ribbon:
  eureka:
    enabled: true