###############################################################################################
# 代码地址（ 任选其一）
# http://git.oschina.net/itmuch/spring-cloud-study/tree/master/microserviceprovider-user
# https://github.com/eacdy/spring-cloudstudy/tree/master/microservice-provider-user
###############################################################################################
server:
  port: 18092
spring:
  application:
    name: micsvc-provider-user                           # 项目名称尽量用小写
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                                             # 指定数据源
    platform: h2                                          # 指定数据源类型
    schema: classpath:schema.sql                          # 指定h2数据库的建表脚本
    data: classpath:data.sql                              # 指定h2数据库的insert脚本

# 指定日志级别
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
# 指定注册中心的地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8091/eureka/,http://peer2:8092/eureka
  instance:
    preferIpAddress: true