###############################################################################################
# 参考文档：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_standalone_mode
# 参考文档：http://my.oschina.net/buwei/blog/618756
###############################################################################################

#----------------------------------------------------
#一、单节点配置
#----------------------------------------------------
# 指定该Eureka实例的端口
#server:
#  port: 8091

# 指定该Eureka实例的主机名
#eureka:
#  instance:
#    hostname: svc-discovery
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#----------------------------------------------------
#二、集群配置
#----------------------------------------------------
---
spring:
  profiles: peer1                                 # 指定profile=peer1
server:
  port: 8091
eureka:
  instance:
    hostname: peer1                               # 指定当profile=peer1时，主机名
  client:
    serviceUrl:
      defaultZone: http://peer2:8092/eureka/      # 将自己注册到peer2这个Eureka上面去

---
spring:
  profiles: peer2
server:
  port: 8092
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8091/eureka/